      - name: Download futures data
        shell: bash
        run: |

          source dates.env

          export TRAIN_START
          export TEST_END

          python - <<'PY'

          import subprocess
          import os
          from datetime import datetime, timedelta

          train_start = datetime.strptime(
              os.environ["TRAIN_START"],
              "%Y%m%d"
          )

          test_end = datetime.strptime(
              os.environ["TEST_END"],
              "%Y%m%d"
          )

          pairs = [
              "ETH/USDT:USDT",
              "BTC/USDT:USDT",
              "SOL/USDT:USDT",
              "XRP/USDT:USDT",
              "BTW/USDT:USDT"
          ]

          current = train_start

          while current < test_end:

              next_date = current + timedelta(
                  days=30
              )

              if next_date > test_end:
                  next_date = test_end

              start = current.strftime(
                  "%Y%m%d"
              )

              end = next_date.strftime(
                  "%Y%m%d"
              )

              timerange = (
                  f"{start}-{end}"
              )

              print("")
              print("=" * 70)
              print(
                  "DOWNLOADING:",
                  timerange
              )
              print("=" * 70)

              command = [
                  "freqtrade",
                  "download-data",
                  "--config",
                  "config.json",
                  "--trading-mode",
                  "futures",
                  "--timeframes",
                  "15m",
                  "--timerange",
                  timerange,
                  "--pairs"
              ]

              command.extend(pairs)

              result = subprocess.run(
                  command
              )

              if result.returncode != 0:

                  raise SystemExit(
                      "Data download failed."
                  )

              current = next_date

          PY
